LITE-23303: Add translation sync command
cloudblue/connect-cli pull request #117
Opened 2022-05-18 14:14 UTC by qarlosh

split in two commits. First one is refactoring, moving all synchronizer stats tracking and printing to a core helper class.
second one is adding the new translation sync command.

2022-05-24 08:21 UTC, marcserrat approved these changes

2022-05-24 08:58 UTC, ffaraoneim requested changes
I think we sould create a folder inside the plugins module for shared functions between plugins instead of put code that is not related with core features of the CLI in the core module.
IMO core features should be those related to generic command input/output, plugins management, configuration. 
Wdyt ?

2022-05-24 10:33 UTC, qarlosh commented
> I think we sould create a folder inside the plugins module for shared functions between plugins instead of put code that is not related with core features of the CLI in the core module. IMO core features should be those related to generic command input/output, plugins management, configuration. Wdyt ?

sounds like a good idea, do I create a `connect/cli/plugins/shared` folder and move there shared functions between plugins?

2022-05-24 15:21 UTC, d3rky requested changes

2022-05-24 15:57 UTC, qarlosh commented on connect/cli/plugins/translation/sync.py
> +            raise click.ClickException('Timeout waiting for pending translation tasks')
ok, I will check this!

2022-05-25 09:21 UTC, d3rky approved these changes

2022-05-25 11:06 UTC, qarlosh commented
moved shared plugins functions to `connect/cli/plugins/shared`

2022-05-25 12:17 UTC, ffaraoneim approved these changes

2022-05-25 12:22 UTC, merged