LITE-19396: Add intro and summary dialogs on EAAS bootstrap
cloudblue/connect-cli pull request #67
Opened 2021-08-27 12:46 UTC by jpdolz

2021-08-30 08:34 UTC, gab832 commented on tests/plugins/project/test_extension_helpers.py
>  def test_bootstrap_direxists_error(fs, mocker, config_mocker):
Do you mean _dir_exists_error?

2021-08-30 08:35 UTC, gab832 approved these changes
It looks good.

2021-08-31 11:59 UTC, marcserrat requested changes

2021-08-31 11:59 UTC, marcserrat commented on connect/cli/plugins/project/utils.py
> +            'message': 'Welcome to the Extension as a Service boilerplate utility.\n'
Welcome to the Connect Extension Project Bootstrap utility

2021-08-31 11:59 UTC, marcserrat commented on connect/cli/plugins/project/utils.py
> +            'You will drive through different screen dialogs where you provide required\n'
Using this utility multiple data will be collected in order to create a project skeleton for your Connect Extension. This skeleton will contain all the needed things to start writing your code.

2021-08-31 11:59 UTC, marcserrat commented on connect/cli/plugins/project/utils.py
> +            'message': 'The selected values for the extension project have been:\n\n'
The provided values for the project are:

2021-09-07 08:18 UTC, merged