LITE-20977: Changed the product custom events as generic
cloudblue/connect-cli pull request #74
Opened 2021-11-10 10:40 UTC by gab832

2021-11-10 17:32 UTC, marcserrat commented on connect/cli/plugins/project/utils.py
> +            'description': 'Product custom events capability',
Will your extension support custom events? Custom events are useful in the use case that an external system needs to interact with your extension running on the cloud

2021-11-15 13:32 UTC, ffaraoneim requested changes

2021-11-15 13:32 UTC, ffaraoneim commented on README.md
> +To run the `connect-cli` current version localy run:
localy -> locally

2021-11-15 13:32 UTC, ffaraoneim commented on README.md
> +If you need to change the boilerplate template used to generate the extension project you have to modify the file ./connect/cli/plugins/project/extension_helpers.py, the function bootstrap_extension_
I prefer to not include this.

2021-11-16 07:58 UTC, ffaraoneim approved these changes

2021-11-17 15:13 UTC, merged