LITE-23305 Add command for list of translations and move `locale-util…
cloudblue/connect-cli pull request #98
Opened 2022-05-05 14:18 UTC by jonatrios

…s` to `core-utils`

2022-05-05 20:44 UTC, marcserrat requested changes
i think we miss name in the translations to understand what translation is about

2022-05-05 20:44 UTC, marcserrat commented on docs/translations_usage.md
> +│TRN-0000-0000-0000│PRD-999-999-999│  product   │English│off │inactive│   ✓   │  ✓  │
i think we miss the context name to understand better what is translation about

2022-05-06 08:21 UTC, d3rky requested changes

2022-05-06 08:21 UTC, d3rky commented on connect/cli/core/utils.py
> +def field_to_check_mark(predicate, false_value=''):
It is nice to have comments for public interfaces for that they are and what are the parameters

2022-05-09 09:44 UTC, d3rky approved these changes

2022-05-09 09:44 UTC, merged